# Loads the default Home Assistant integrations.
default_config:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /runelite_bridge_static/bank-card.js?v=1

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  dashboards:
    runelite-dashboard:
      mode: yaml
      title: RuneLite
      icon: mdi:sword-cross
      show_in_sidebar: true
      require_admin: false
      filename: runelite-dashboard.yaml
